export interface FeaturedCiv {
  id: string;
  name: string;
  leader: string;
  abilityName: string;
  abilityDesc: string;
  uniqueUnit: string;
  uniqueInfra: string;
  region: string;
  era: string;
}

export const FEATURED_CIVS: FeaturedCiv[] = [
  {
    id: "sumer",
    name: "Sumer",
    leader: "Gilgamesh",
    abilityName: "Epic Quest",
    abilityDesc: "Early war-carts and extra rewards from clearing barbarian camps.",
    uniqueUnit: "War-Cart",
    uniqueInfra: "Ziggurat",
    region: "Mesopotamia & Near East",
    era: "Dawn Age",
  },
  {
    id: "akkad",
    name: "Akkad",
    leader: "Sargon",
    abilityName: "Sons of Sargon",
    abilityDesc: "Captured cities keep more buildings; siege bonus near the capital.",
    uniqueUnit: "Sargonic Guard",
    uniqueInfra: "Palace Archive",
    region: "Mesopotamia & Near East",
    era: "Dawn Age",
  },
  {
    id: "babylon",
    name: "Babylon",
    leader: "Hammurabi",
    abilityName: "Enuma Anu Enlil",
    abilityDesc: "Eurekas trigger faster; science output is traded for eureka progress.",
    uniqueUnit: "Bowman",
    uniqueInfra: "Walls of Babylon",
    region: "Mesopotamia & Near East",
    era: "Bronze Age",
  },
  {
    id: "assyria",
    name: "Assyria",
    leader: "Ashurbanipal",
    abilityName: "Treatises & Terror",
    abilityDesc: "Siege units are stronger; captured cities grant science.",
    uniqueUnit: "Siege Tower",
    uniqueInfra: "Royal Library",
    region: "Mesopotamia & Near East",
    era: "Iron / Classical",
  },
  {
    id: "hittites",
    name: "Hittites",
    leader: "Suppiluliuma",
    abilityName: "Iron of Hatti",
    abilityDesc: "Early iron access and faster ironworking production.",
    uniqueUnit: "Hittite Chariot",
    uniqueInfra: "Storm Temple",
    region: "Mesopotamia & Near East",
    era: "Bronze Age",
  },
  {
    id: "elam",
    name: "Elam",
    leader: "Untash",
    abilityName: "Highland Archers",
    abilityDesc: "Ranged units gain extra strength in hill terrain.",
    uniqueUnit: "Susian Archer",
    uniqueInfra: "Chogha Zanbil",
    region: "Mesopotamia & Near East",
    era: "Bronze Age",
  },
  {
    id: "phoenicia",
    name: "Phoenicia",
    leader: "Dido",
    abilityName: "Mediterranean Colonies",
    abilityDesc: "Cheap coastal settlers, extended naval range, and extra trade gold.",
    uniqueUnit: "Bireme",
    uniqueInfra: "Cothon",
    region: "Mesopotamia & Near East",
    era: "Bronze Age",
  },
  {
    id: "lydia",
    name: "Lydia",
    leader: "Croesus",
    abilityName: "Coinage",
    abilityDesc: "Markets and banks generate extra gold; trade routes are more profitable.",
    uniqueUnit: "Heavy Cavalry",
    uniqueInfra: "Mint",
    region: "Mesopotamia & Near East",
    era: "Iron / Classical",
  },
  {
    id: "median_empire",
    name: "Median Empire",
    leader: "Cyaxares",
    abilityName: "Horse Lords",
    abilityDesc: "Mounted units gain extra movement on open terrain.",
    uniqueUnit: "Median Lancer",
    uniqueInfra: "Royal Stable",
    region: "Persia & Iran",
    era: "Iron / Classical",
  },
  {
    id: "persia",
    name: "Persia",
    leader: "Cyrus",
    abilityName: "Satrapies",
    abilityDesc: "+20% gold; melee units +2 combat strength.",
    uniqueUnit: "Immortal",
    uniqueInfra: "Pairidaeza",
    region: "Persia & Iran",
    era: "Iron / Classical",
  },
  {
    id: "parthia",
    name: "Parthia",
    leader: "Mithridates",
    abilityName: "Parthian Shot",
    abilityDesc: "Horse archers ignore retreat penalties and fight effectively while moving.",
    uniqueUnit: "Parthian Horse Archer",
    uniqueInfra: "Caravanserai",
    region: "Persia & Iran",
    era: "Iron / Classical",
  },
  {
    id: "sassanid_persia",
    name: "Sassanid Persia",
    leader: "Khosrow",
    abilityName: "Eranshahr",
    abilityDesc: "Heavy cavalry are stronger; golden ages boost culture and science.",
    uniqueUnit: "Savaran Cataphract",
    uniqueInfra: "Fire Temple",
    region: "Persia & Iran",
    era: "Medieval / Faith",
  },
  {
    id: "egypt",
    name: "Egypt",
    leader: "Hatshepsut",
    abilityName: "Iteru",
    abilityDesc: "+20% production in all cities.",
    uniqueUnit: "Maryannu Chariot",
    uniqueInfra: "Sphinx",
    region: "Africa",
    era: "Bronze Age",
  },
  {
    id: "kush_nubia",
    name: "Kush / Nubia",
    leader: "Amanirenas",
    abilityName: "City of the Dead",
    abilityDesc: "Pyramids are cheaper; trade routes through desert grant production.",
    uniqueUnit: "Nubian Archer",
    uniqueInfra: "Nubian Pyramid",
    region: "Africa",
    era: "Bronze Age",
  },
  {
    id: "carthage",
    name: "Carthage",
    leader: "Hannibal",
    abilityName: "Phoenician Heritage",
    abilityDesc: "Coastal capital bonus, stronger naval movement, and mountain-crossing armies.",
    uniqueUnit: "War Elephant",
    uniqueInfra: "Cothon",
    region: "Africa",
    era: "Iron / Classical",
  },
  {
    id: "aksum",
    name: "Aksum",
    leader: "Ezana",
    abilityName: "Red Sea Trade",
    abilityDesc: "International trade routes grant extra gold and faith.",
    uniqueUnit: "Aksumite Spearman",
    uniqueInfra: "Stelae",
    region: "Africa",
    era: "Iron / Classical",
  },
  {
    id: "ethiopia_zagwe",
    name: "Ethiopia (Zagwe)",
    leader: "Lalibela",
    abilityName: "Aksumite Legacy",
    abilityDesc: "Faith from mountains and stronger combat at higher altitude.",
    uniqueUnit: "Oromo Cavalry",
    uniqueInfra: "Rock-Hewn Church",
    region: "Africa",
    era: "Medieval / Faith",
  },
  {
    id: "mali",
    name: "Mali",
    leader: "Mansa Musa",
    abilityName: "Sahel Merchants",
    abilityDesc: "+10% gold and +2 gold from each worked desert tile.",
    uniqueUnit: "Mandekalu Cavalry",
    uniqueInfra: "Suguba",
    region: "Africa",
    era: "Medieval / Faith",
  },
  {
    id: "ghana_empire",
    name: "Ghana Empire",
    leader: "Tunka Manin",
    abilityName: "Gold of Wagadu",
    abilityDesc: "Gold from mining and trade; defensive bonus in home territory.",
    uniqueUnit: "Soninke Warrior",
    uniqueInfra: "Gold Market",
    region: "Africa",
    era: "Medieval / Faith",
  },
  {
    id: "songhai",
    name: "Songhai",
    leader: "Askia",
    abilityName: "River of Gold",
    abilityDesc: "River trade yields extra gold; embarked units are stronger.",
    uniqueUnit: "Songhai Cavalry",
    uniqueInfra: "River Port",
    region: "Africa",
    era: "Medieval / Faith",
  },
  {
    id: "great_zimbabwe",
    name: "Great Zimbabwe",
    leader: "Nyatsimba",
    abilityName: "Cattle & Stone",
    abilityDesc: "Pastures generate extra gold; trade route capacity is increased.",
    uniqueUnit: "Zimbabwe Spearman",
    uniqueInfra: "Great Enclosure",
    region: "Africa",
    era: "Medieval / Faith",
  },
  {
    id: "kanem_bornu",
    name: "Kanem-Bornu",
    leader: "Idris Alooma",
    abilityName: "Trans-Saharan",
    abilityDesc: "Desert trade routes yield gold; early firearms appear in the Exploration era.",
    uniqueUnit: "Kanembu Guard",
    uniqueInfra: "Sahel Caravan Post",
    region: "Africa",
    era: "Medieval / Faith",
  },
  {
    id: "minoans",
    name: "Minoans",
    leader: "Minos",
    abilityName: "Thalassocracy",
    abilityDesc: "First naval power; coastal trade grants extra culture and gold.",
    uniqueUnit: "Minoan Bireme",
    uniqueInfra: "Labyrinth Palace",
    region: "Europe",
    era: "Bronze Age",
  },
  {
    id: "mycenaean_greece",
    name: "Mycenaean Greece",
    leader: "Agamemnon",
    abilityName: "Heroic Age",
    abilityDesc: "Heroes are cheaper to recruit; melee units gain strength during war.",
    uniqueUnit: "Mycenaean Spearman",
    uniqueInfra: "Megaron",
    region: "Europe",
    era: "Bronze Age",
  },
  {
    id: "greece",
    name: "Greece",
    leader: "Pericles",
    abilityName: "Plato's Republic",
    abilityDesc: "+20% science; melee units +2 combat strength.",
    uniqueUnit: "Hoplite",
    uniqueInfra: "Acropolis",
    region: "Europe",
    era: "Iron / Classical",
  },
  {
    id: "sparta",
    name: "Sparta",
    leader: "Leonidas",
    abilityName: "Agoge",
    abilityDesc: "Military units are cheaper and earn experience faster; defensive last-stand bonus.",
    uniqueUnit: "Spartan Hoplite",
    uniqueInfra: "Syssitia",
    region: "Europe",
    era: "Iron / Classical",
  },
  {
    id: "macedon",
    name: "Macedon",
    leader: "Alexander",
    abilityName: "Hellenistic Fusion",
    abilityDesc: "No war-weariness during conquests; capturing cities grants science and culture.",
    uniqueUnit: "Hypaspist",
    uniqueInfra: "Basilikoi Paides",
    region: "Europe",
    era: "Iron / Classical",
  },
  {
    id: "etruscans",
    name: "Etruscans",
    leader: "Lars Porsena",
    abilityName: "Twelve Cities",
    abilityDesc: "Extra trade routes and cheaper roads between cities.",
    uniqueUnit: "Etruscan Hoplite",
    uniqueInfra: "Tumulus",
    region: "Europe",
    era: "Iron / Classical",
  },
  {
    id: "rome",
    name: "Rome",
    leader: "Trajan",
    abilityName: "All Roads Lead to Rome",
    abilityDesc: "New cities are founded with a free Monument.",
    uniqueUnit: "Legionary",
    uniqueInfra: "Roman Bath",
    region: "Europe",
    era: "Iron / Classical",
  },
  {
    id: "celts_gauls",
    name: "Celts / Gauls",
    leader: "Vercingetorix",
    abilityName: "Druidic Lore",
    abilityDesc: "Faith from forests; oppida provide strong defensive positions.",
    uniqueUnit: "Gaesatae",
    uniqueInfra: "Oppidum",
    region: "Europe",
    era: "Iron / Classical",
  },
  {
    id: "byzantium",
    name: "Byzantium",
    leader: "Justinian",
    abilityName: "Taxis",
    abilityDesc: "Units gain bonus strength against civilizations of other religions.",
    uniqueUnit: "Cataphract",
    uniqueInfra: "Hippodrome",
    region: "Europe",
    era: "Medieval / Faith",
  },
  {
    id: "norse",
    name: "Norse",
    leader: "Harald Hardrada",
    abilityName: "Knarr",
    abilityDesc: "+15% gold from raiding; melee units +2 combat strength.",
    uniqueUnit: "Longship",
    uniqueInfra: "Stave Church",
    region: "Europe",
    era: "Medieval / Faith",
  },
  {
    id: "franks",
    name: "Franks",
    leader: "Charlemagne",
    abilityName: "Carolingian Reform",
    abilityDesc: "Knights appear earlier; cities generate extra faith.",
    uniqueUnit: "Frankish Paladin",
    uniqueInfra: "Palatine Chapel",
    region: "Europe",
    era: "Medieval / Faith",
  },
  {
    id: "goths",
    name: "Goths",
    leader: "Theodoric",
    abilityName: "Foederati",
    abilityDesc: "Captured units may join your forces; armies are highly mobile.",
    uniqueUnit: "Gothic Rider",
    uniqueInfra: "Wagon Fort",
    region: "Europe",
    era: "Medieval / Faith",
  },
  {
    id: "anglo_saxon_england",
    name: "Anglo-Saxon / England",
    leader: "Alfred",
    abilityName: "Workshop of the World",
    abilityDesc: "Strong production and naval supremacy; longbow defense.",
    uniqueUnit: "Longbowman",
    uniqueInfra: "Manor House",
    region: "Europe",
    era: "Medieval / Faith",
  },
  {
    id: "france",
    name: "France",
    leader: "Joan of Arc",
    abilityName: "Grand Tour",
    abilityDesc: "Wonders grant extra culture; châteaux improve tile culture output.",
    uniqueUnit: "Garde Écossaise",
    uniqueInfra: "Château",
    region: "Europe",
    era: "Medieval / Faith",
  },
  {
    id: "castile_spain",
    name: "Castile / Spain",
    leader: "Isabella",
    abilityName: "El Escorial",
    abilityDesc: "Combat bonus against other religions; treasure fleets bring gold from distant colonies.",
    uniqueUnit: "Conquistador",
    uniqueInfra: "Mission",
    region: "Europe",
    era: "Exploration",
  },
  {
    id: "portugal",
    name: "Portugal",
    leader: "Henry the Navigator",
    abilityName: "Casa da Índia",
    abilityDesc: "Long ocean trade range and increased yields from overseas trade.",
    uniqueUnit: "Nau",
    uniqueInfra: "Feitoria",
    region: "Europe",
    era: "Exploration",
  },
  {
    id: "venice",
    name: "Venice",
    leader: "Enrico Dandolo",
    abilityName: "Serenissima",
    abilityDesc: "Extra trade routes and merchant gold; settlers are replaced by city purchases.",
    uniqueUnit: "Venetian Galleass",
    uniqueInfra: "Arsenale",
    region: "Europe",
    era: "Medieval / Faith",
  },
  {
    id: "genoa",
    name: "Genoa",
    leader: "Andrea Doria",
    abilityName: "Bank of San Giorgio",
    abilityDesc: "Banking generates extra gold; mercenaries are cheaper to hire.",
    uniqueUnit: "Genoese Crossbowman",
    uniqueInfra: "Banco",
    region: "Europe",
    era: "Medieval / Faith",
  },
  {
    id: "dutch_republic",
    name: "Dutch Republic",
    leader: "William the Silent",
    abilityName: "Grachten",
    abilityDesc: "Rivers and polders boost yields; trade routes grant extra gold.",
    uniqueUnit: "Sea Beggar",
    uniqueInfra: "Polder",
    region: "Europe",
    era: "Exploration",
  },
  {
    id: "holy_roman_empire",
    name: "Holy Roman Empire / Germany",
    leader: "Barbarossa",
    abilityName: "Free Imperial Cities",
    abilityDesc: "Extra district per city and increased production.",
    uniqueUnit: "Landsknecht",
    uniqueInfra: "Hansa",
    region: "Europe",
    era: "Medieval / Faith",
  },
  {
    id: "kievan_rus",
    name: "Kievan Rus",
    leader: "Yaroslav",
    abilityName: "Lavra",
    abilityDesc: "Faith from forests and tundra; territory grows quickly.",
    uniqueUnit: "Druzhina",
    uniqueInfra: "Lavra",
    region: "Europe",
    era: "Medieval / Faith",
  },
  {
    id: "poland_lithuania",
    name: "Poland-Lithuania",
    leader: "Jadwiga",
    abilityName: "Golden Liberty",
    abilityDesc: "Culture flips conquered tiles; faith converts into culture.",
    uniqueUnit: "Winged Hussar",
    uniqueInfra: "Sukiennice",
    region: "Europe",
    era: "Medieval / Faith",
  },
  {
    id: "hungary",
    name: "Hungary",
    leader: "Matthias Corvinus",
    abilityName: "Pearl of the Danube",
    abilityDesc: "City-state levies are cheaper and stronger.",
    uniqueUnit: "Black Army",
    uniqueInfra: "Thermal Bath",
    region: "Europe",
    era: "Medieval / Faith",
  },
  {
    id: "han_china",
    name: "Han China",
    leader: "Qin Shi Huang",
    abilityName: "Dynastic Cycle",
    abilityDesc: "+15% production and +10% science.",
    uniqueUnit: "Cho-Ko-Nu",
    uniqueInfra: "Great Wall",
    region: "Asia",
    era: "Iron / Classical",
  },
  {
    id: "china_tang_song",
    name: "China (Tang/Song)",
    leader: "Taizong",
    abilityName: "Middle Kingdom",
    abilityDesc: "Capital-adjacent cities gain yields; gunpowder and printing arrive earlier.",
    uniqueUnit: "Fire Lancer",
    uniqueInfra: "Imperial Examination Hall",
    region: "Asia",
    era: "Medieval / Faith",
  },
  {
    id: "china_ming",
    name: "China (Ming)",
    leader: "Yongle",
    abilityName: "Treasure Fleets",
    abilityDesc: "Massive coastal cities; ocean trade and exploration yield extra gold.",
    uniqueUnit: "War Junk",
    uniqueInfra: "Porcelain Tower",
    region: "Asia",
    era: "Exploration",
  },
  {
    id: "maurya",
    name: "Maurya",
    leader: "Ashoka",
    abilityName: "Dharma",
    abilityDesc: "+20% food; cavalry (elephants) +2 combat strength.",
    uniqueUnit: "War Elephant",
    uniqueInfra: "Stepwell",
    region: "Asia",
    era: "Iron / Classical",
  },
  {
    id: "gupta_india",
    name: "Gupta India",
    leader: "Chandragupta II",
    abilityName: "Golden Age of India",
    abilityDesc: "Bonus science and culture; mathematics advances earlier.",
    uniqueUnit: "Gupta Elephant Archer",
    uniqueInfra: "University-Temple",
    region: "Asia",
    era: "Iron / Classical",
  },
  {
    id: "chola",
    name: "Chola",
    leader: "Rajaraja",
    abilityName: "Maritime Empire",
    abilityDesc: "Naval reach spans oceans; overseas conquest is more profitable.",
    uniqueUnit: "Chola Warship",
    uniqueInfra: "Brihadeeswara Temple",
    region: "Asia",
    era: "Medieval / Faith",
  },
  {
    id: "japan",
    name: "Japan",
    leader: "Tokugawa",
    abilityName: "Bushido",
    abilityDesc: "Units fight at full strength even when damaged; districts cluster for bonuses.",
    uniqueUnit: "Samurai",
    uniqueInfra: "Tenshu Castle",
    region: "Asia",
    era: "Medieval / Faith",
  },
  {
    id: "korea",
    name: "Korea (Goryeo/Joseon)",
    leader: "Sejong",
    abilityName: "Hwarang",
    abilityDesc: "Science from governors and mines; turtle ships bolster coastal defense.",
    uniqueUnit: "Turtle Ship",
    uniqueInfra: "Seowon",
    region: "Asia",
    era: "Medieval / Faith",
  },
  {
    id: "tibet",
    name: "Tibet",
    leader: "Songtsen Gampo",
    abilityName: "Roof of the World",
    abilityDesc: "Mountains become workable and grant faith; combat bonus at high altitude.",
    uniqueUnit: "Tibetan Cavalry",
    uniqueInfra: "Potala",
    region: "Asia",
    era: "Medieval / Faith",
  },
  {
    id: "dai_viet_vietnam",
    name: "Dai Viet (Vietnam)",
    leader: "Le Loi",
    abilityName: "Nine Dragons",
    abilityDesc: "Forest and jungle ambush bonus; strong defensive capabilities.",
    uniqueUnit: "Voi Chiến",
    uniqueInfra: "Thành",
    region: "Asia",
    era: "Medieval / Faith",
  },
  {
    id: "khmer",
    name: "Khmer",
    leader: "Jayavarman VII",
    abilityName: "Grand Barays",
    abilityDesc: "Rivers provide extra food and faith; cities can grow very large.",
    uniqueUnit: "Domrey",
    uniqueInfra: "Prasat",
    region: "Asia",
    era: "Medieval / Faith",
  },
  {
    id: "srivijaya",
    name: "Srivijaya",
    leader: "Balaputra",
    abilityName: "Maritime Mandala",
    abilityDesc: "Control of sea lanes grants trade gold; coastal cities thrive.",
    uniqueUnit: "Jong",
    uniqueInfra: "Candi",
    region: "Asia",
    era: "Medieval / Faith",
  },
  {
    id: "majapahit",
    name: "Majapahit",
    leader: "Hayam Wuruk",
    abilityName: "Nusantara",
    abilityDesc: "Bonus per coastal city; trade across islands yields extra gold.",
    uniqueUnit: "Majapahit Jong",
    uniqueInfra: "Harbor-Temple",
    region: "Asia",
    era: "Medieval / Faith",
  },
  {
    id: "pagan_burma",
    name: "Pagan (Burma)",
    leader: "Anawrahta",
    abilityName: "Land of Pagodas",
    abilityDesc: "Faith from building construction; war elephants dominate the battlefield.",
    uniqueUnit: "Burmese War Elephant",
    uniqueInfra: "Pagoda",
    region: "Asia",
    era: "Medieval / Faith",
  },
  {
    id: "ayutthaya_siam",
    name: "Ayutthaya (Siam)",
    leader: "Ramkhamhaeng",
    abilityName: "Father Governs Children",
    abilityDesc: "City-state alliances grant science, culture, and faith.",
    uniqueUnit: "Siamese War Elephant",
    uniqueInfra: "Wat",
    region: "Asia",
    era: "Medieval / Faith",
  },
  {
    id: "scythians",
    name: "Scythians",
    leader: "Tomyris",
    abilityName: "People of the Steppe",
    abilityDesc: "Extra light cavalry per build; mounted units heal after kills.",
    uniqueUnit: "Scythian Horse Archer",
    uniqueInfra: "Kurgan",
    region: "Central Asia",
    era: "Iron / Classical",
  },
  {
    id: "xiongnu",
    name: "Xiongnu",
    leader: "Modu Chanyu",
    abilityName: "Steppe Confederacy",
    abilityDesc: "Raiding yields extra gold; horse units are cheaper to produce.",
    uniqueUnit: "Xiongnu Horse Archer",
    uniqueInfra: "Felt Tent",
    region: "Central Asia",
    era: "Iron / Classical",
  },
  {
    id: "huns",
    name: "Huns",
    leader: "Attila",
    abilityName: "Scourge of God",
    abilityDesc: "Siege power from captured cities; razing cities grants production.",
    uniqueUnit: "Hunnic Horde",
    uniqueInfra: "Ordu",
    region: "Central Asia",
    era: "Medieval / Faith",
  },
  {
    id: "gokturks",
    name: "Göktürks",
    leader: "Bumin Qaghan",
    abilityName: "Sky Father",
    abilityDesc: "Cavalry gain combat strength; borders expand quickly.",
    uniqueUnit: "Turkic Lancer",
    uniqueInfra: "Stone Stele",
    region: "Central Asia",
    era: "Medieval / Faith",
  },
  {
    id: "seljuks",
    name: "Seljuks",
    leader: "Alp Arslan",
    abilityName: "Ghazi",
    abilityDesc: "Combat bonus against other religions; conquest grants faith.",
    uniqueUnit: "Ghulam",
    uniqueInfra: "Madrasa",
    region: "Central Asia",
    era: "Medieval / Faith",
  },
  {
    id: "mongols",
    name: "Mongols",
    leader: "Genghis Khan",
    abilityName: "Örtöö",
    abilityDesc: "Cavalry +1 movement and +2 combat strength.",
    uniqueUnit: "Keshig",
    uniqueInfra: "Ordu",
    region: "Central Asia",
    era: "Medieval / Faith",
  },
  {
    id: "timurids",
    name: "Timurids",
    leader: "Tamerlane",
    abilityName: "Sword of Islam",
    abilityDesc: "Siege bonus; plunder enriches cities and advances science.",
    uniqueUnit: "Timurid Siege Train",
    uniqueInfra: "Registan",
    region: "Central Asia",
    era: "Medieval / Faith",
  },
  {
    id: "ottomans",
    name: "Ottomans",
    leader: "Mehmed II",
    abilityName: "Great Bombard",
    abilityDesc: "Siege and gunpowder supremacy; conquered cities stay loyal.",
    uniqueUnit: "Janissary",
    uniqueInfra: "Grand Bazaar",
    region: "Central Asia",
    era: "Exploration",
  },
  {
    id: "olmec",
    name: "Olmec",
    leader: "Council",
    abilityName: "Mother Culture",
    abilityDesc: "Early culture and faith; colossal heads generate influence.",
    uniqueUnit: "Olmec Spearman",
    uniqueInfra: "Colossal Head",
    region: "The Americas",
    era: "Bronze Age",
  },
  {
    id: "maya",
    name: "Maya",
    leader: "Pacal the Great",
    abilityName: "Mayab",
    abilityDesc: "Cities near the capital gain yields; observatories boost science.",
    uniqueUnit: "Holkan",
    uniqueInfra: "Observatory",
    region: "The Americas",
    era: "Medieval / Faith",
  },
  {
    id: "zapotec",
    name: "Zapotec",
    leader: "Cocijo priesthood",
    abilityName: "Cloud People",
    abilityDesc: "Hill cities gain defense and extra culture.",
    uniqueUnit: "Zapotec Warrior",
    uniqueInfra: "Danzante Temple",
    region: "The Americas",
    era: "Bronze Age",
  },
  {
    id: "teotihuacan",
    name: "Teotihuacan",
    leader: "Priest-Kings",
    abilityName: "City of the Gods",
    abilityDesc: "Wonders and pyramids are cheaper; culture output is strong.",
    uniqueUnit: "Pyramid Guard",
    uniqueInfra: "Avenue of the Dead",
    region: "The Americas",
    era: "Iron / Classical",
  },
  {
    id: "toltec",
    name: "Toltec",
    leader: "Topiltzin",
    abilityName: "Toltecayotl",
    abilityDesc: "Military culture; veteran units gain extra combat strength.",
    uniqueUnit: "Toltec Warrior",
    uniqueInfra: "Atlantean Hall",
    region: "The Americas",
    era: "Medieval / Faith",
  },
  {
    id: "aztec",
    name: "Aztec",
    leader: "Montezuma",
    abilityName: "Legend of the Eagle",
    abilityDesc: "Melee units +3 combat strength.",
    uniqueUnit: "Eagle Warrior",
    uniqueInfra: "Tlachtli",
    region: "The Americas",
    era: "Medieval / Faith",
  },
  {
    id: "inca",
    name: "Inca",
    leader: "Pachacuti",
    abilityName: "Mit'a",
    abilityDesc: "Mountains become workable; terrace farms feed large cities.",
    uniqueUnit: "Warak'aq",
    uniqueInfra: "Terrace Farm",
    region: "The Americas",
    era: "Medieval / Faith",
  },
  {
    id: "muisca",
    name: "Muisca",
    leader: "Zipa",
    abilityName: "El Dorado",
    abilityDesc: "Faith converts into gold; lake and highland tiles yield more.",
    uniqueUnit: "Guecha Warrior",
    uniqueInfra: "Salt Temple",
    region: "The Americas",
    era: "Medieval / Faith",
  },
  {
    id: "mississippian_cahokia",
    name: "Mississippian (Cahokia)",
    leader: "Great Sun",
    abilityName: "Mound Builders",
    abilityDesc: "Earthwork improvements generate culture and faith; river trade is strong.",
    uniqueUnit: "Cahokian Warrior",
    uniqueInfra: "Earthwork Mound",
    region: "The Americas",
    era: "Medieval / Faith",
  },
  {
    id: "haudenosaunee",
    name: "Haudenosaunee (Iroquois)",
    leader: "Hiawatha",
    abilityName: "Great League",
    abilityDesc: "Forest movement and combat bonus; longhouses boost production.",
    uniqueUnit: "Mohawk Warrior",
    uniqueInfra: "Longhouse",
    region: "The Americas",
    era: "Medieval / Faith",
  },
  {
    id: "pueblo",
    name: "Pueblo",
    leader: "Council",
    abilityName: "Cliff Dwellers",
    abilityDesc: "Desert and mesa tiles grant defense and extra housing.",
    uniqueUnit: "Pueblo Skirmisher",
    uniqueInfra: "Cliff Palace",
    region: "The Americas",
    era: "Medieval / Faith",
  },
  {
    id: "polynesia",
    name: "Polynesia",
    leader: "Hotu Matua",
    abilityName: "Wayfinding",
    abilityDesc: "Ocean embark and sight from the start; settle distant islands early.",
    uniqueUnit: "Koa Warrior",
    uniqueInfra: "Marae",
    region: "Oceania",
    era: "Medieval / Faith",
  },
  {
    id: "maori",
    name: "Māori",
    leader: "Kupe",
    abilityName: "Mana",
    abilityDesc: "Start at sea; unimproved forests and reefs grant yields; pā defend strongly.",
    uniqueUnit: "Toa",
    uniqueInfra: "Pā",
    region: "Oceania",
    era: "Medieval / Faith",
  },
  {
    id: "hawaii",
    name: "Hawaiʻi",
    leader: "Kamehameha",
    abilityName: "Aloha ʻĀina",
    abilityDesc: "Coastal cities gain amenities; island unification yields extra gold.",
    uniqueUnit: "Hawaiian Koa",
    uniqueInfra: "Heiau",
    region: "Oceania",
    era: "Medieval / Faith",
  },
];;;

export const PILLARS = [
  {
    title: 'Explore',
    desc: 'Chart unknown lands, dispatch scouts, and reveal resources from wheat fields to iron mines.',
    asset: 'assets/units/scout.png',
  },
  {
    title: 'Expand',
    desc: 'Found cities across continents, claim territory, and build roads that bind your empire together.',
    asset: 'assets/units/settler.png',
  },
  {
    title: 'Exploit',
    desc: 'Assign citizens, improve tiles, trade luxuries, and balance food, production, gold, and science.',
    asset: 'assets/resources/wheat.png',
  },
  {
    title: 'Exterminate',
    desc: 'Wage tactical wars with unique units, promotions, and combined-arms combat across land and sea.',
    asset: 'assets/units/warrior.png',
  },
] as const;

export const ERAS = [
  { name: 'Stone / Dawn', years: '4000–3000 BCE', desc: 'First tribes, farms, and mud-brick cities.', image: 'age_stone_dawn' },
  { name: 'Bronze Age', years: '3000–1200 BCE', desc: 'Chariots, ziggurats, and the first empires.', image: 'age_bronze' },
  { name: 'Iron / Classical', years: '1200 BCE–500 CE', desc: 'Legions, phalanxes, philosophy, and great roads.', image: 'age_iron_classical' },
  { name: 'Medieval / Faith', years: '500–1300 CE', desc: 'Knights, castles, samurai, and cathedrals.', image: 'age_medieval' },
  { name: 'Exploration', years: '1300–1550 CE', desc: 'Caravels, gunpowder, printing, and global trade.', image: 'age_exploration' },
] as const;

export const ALL_LEADERS = [
  'akkad', 'aksum', 'anglo_saxon_england', 'assyria', 'ayutthaya_siam', 'aztec', 'babylon', 'byzantium',
  'carthage', 'castile_spain', 'celts_gauls', 'china_ming', 'china_tang_song', 'chola', 'dai_viet_vietnam',
  'dutch_republic', 'egypt', 'elam', 'ethiopia_zagwe', 'etruscans', 'france', 'franks', 'genoa',
  'ghana_empire', 'gokturks', 'goths', 'great_zimbabwe', 'greece', 'gupta_india', 'han_china', 'haudenosaunee',
  'hawaii', 'hittites', 'holy_roman_empire', 'hungary', 'huns', 'inca', 'japan', 'kanem_bornu', 'khmer',
  'kievan_rus', 'korea', 'kush_nubia', 'lydia', 'macedon', 'majapahit', 'mali', 'maori', 'maurya', 'maya',
  'median_empire', 'minoans', 'mississippian_cahokia', 'mongols', 'muisca', 'mycenaean_greece', 'norse',
  'olmec', 'ottomans', 'pagan_burma', 'parthia', 'persia', 'phoenicia', 'poland_lithuania', 'polynesia',
  'portugal', 'pueblo', 'rome', 'sassanid_persia', 'scythians', 'seljuks', 'songhai', 'sparta', 'srivijaya',
  'sumer', 'teotihuacan', 'tibet', 'timurids', 'toltec', 'venice', 'xiongnu', 'zapotec',
];
