export interface FeaturedCiv {
  id: string;
  name: string;
  leader: string;
  abilityName: string;
  abilityDesc: string;
  uniqueUnit: string;
  uniqueInfra: string;
  region: string;
  era: string;
}

export const FEATURED_CIVS: FeaturedCiv[] = [
  {
    id: "sumer",
    name: "Sumer",
    leader: "Gilgamesh",
    abilityName: "Epic Quest",
    abilityDesc: "Early war-carts and extra rewards from clearing barbarian camps.",
    uniqueUnit: "War-Cart",
    uniqueInfra: "Ziggurat",
    region: "Mesopotamia & Near East",
    era: "Dawn Age",
  },
  {
    id: "akkad",
    name: "Akkad",
    leader: "Sargon",
    abilityName: "Sons of Sargon",
    abilityDesc: "Captured cities keep more buildings; siege bonus near the capital.",
    uniqueUnit: "Sargonic Guard",
    uniqueInfra: "Palace Archive",
    region: "Mesopotamia & Near East",
    era: "Dawn Age",
  },
  {
    id: "babylon",
    name: "Babylon",
    leader: "Hammurabi",
    abilityName: "Enuma Anu Enlil",
    abilityDesc: "Eurekas trigger faster; science output is traded for eureka progress.",
    uniqueUnit: "Bowman",
    uniqueInfra: "Walls of Babylon",
    region: "Mesopotamia & Near East",
    era: "Bronze Age",
  },
  {
    id: "assyria",
    name: "Assyria",
    leader: "Ashurbanipal",
    abilityName: "Treatises & Terror",
    abilityDesc: "Siege units are stronger; captured cities grant science.",
    uniqueUnit: "Siege Tower",
    uniqueInfra: "Royal Library",
    region: "Mesopotamia & Near East",
    era: "Iron / Classical",
  },
  {
    id: "hittites",
    name: "Hittites",
    leader: "Suppiluliuma",
    abilityName: "Iron of Hatti",
    abilityDesc: "Early iron access and faster ironworking production.",
    uniqueUnit: "Hittite Chariot",
    uniqueInfra: "Storm Temple",
    region: "Mesopotamia & Near East",
    era: "Bronze Age",
  },
  {
    id: "elam",
    name: "Elam",
    leader: "Untash",
    abilityName: "Highland Archers",
    abilityDesc: "Ranged units gain extra strength in hill terrain.",
    uniqueUnit: "Susian Archer",
    uniqueInfra: "Chogha Zanbil",
    region: "Mesopotamia & Near East",
    era: "Bronze Age",
  },
  {
    id: "phoenicia",
    name: "Phoenicia",
    leader: "Dido",
    abilityName: "Mediterranean Colonies",
    abilityDesc: "Cheap coastal settlers, extended naval range, and extra trade gold.",
    uniqueUnit: "Bireme",
    uniqueInfra: "Cothon",
    region: "Mesopotamia & Near East",
    era: "Bronze Age",
  },
  {
    id: "lydia",
    name: "Lydia",
    leader: "Croesus",
    abilityName: "Coinage",
    abilityDesc: "Markets and banks generate extra gold; trade routes are more profitable.",
    uniqueUnit: "Heavy Cavalry",
    uniqueInfra: "Mint",
    region: "Mesopotamia & Near East",
    era: "Iron / Classical",
  },
  {
    id: "median_empire",
    name: "Median Empire",
    leader: "Cyaxares",
    abilityName: "Horse Lords",
    abilityDesc: "Mounted units gain extra movement on open terrain.",
    uniqueUnit: "Median Lancer",
    uniqueInfra: "Royal Stable",
    region: "Persia & Iran",
    era: "Iron / Classical",
  },
  {
    id: "persia",
    name: "Persia",
    leader: "Cyrus",
    abilityName: "Satrapies",
    abilityDesc: "+20% gold; melee units +2 combat strength.",
    uniqueUnit: "Immortal",
    uniqueInfra: "Pairidaeza",
    region: "Persia & Iran",
    era: "Iron / Classical",
  },
  {
    id: "parthia",
    name: "Parthia",
    leader: "Mithridates",
    abilityName: "Parthian Shot",
    abilityDesc: "Horse archers ignore retreat penalties and fight effectively while moving.",
    uniqueUnit: "Parthian Horse Archer",
    uniqueInfra: "Caravanserai",
    region: "Persia & Iran",
    era: "Iron / Classical",
  },
  {
    id: "sassanid_persia",
    name: "Sassanid Persia",
    leader: "Khosrow",
    abilityName: "Eranshahr",
    abilityDesc: "Heavy cavalry are stronger; golden ages boost culture and science.",
    uniqueUnit: "Savaran Cataphract",
    uniqueInfra: "Fire Temple",
    region: "Persia & Iran",
    era: "Medieval / Faith",
  },
  {
    id: "egypt",
    name: "Egypt",
    leader: "Hatshepsut",
    abilityName: "Iteru",
    abilityDesc: "+20% production in all cities.",
    uniqueUnit: "Maryannu Chariot",
    uniqueInfra: "Sphinx",
    region: "Africa",
    era: "Bronze Age",
  },
  {
    id: "kush_nubia",
    name: "Kush / Nubia",
    leader: "Amanirenas",
    abilityName: "City of the Dead",
    abilityDesc: "Pyramids are cheaper; trade routes through desert grant production.",
    uniqueUnit: "Nubian Archer",
    uniqueInfra: "Nubian Pyramid",
    region: "Africa",
    era: "Bronze Age",
  },
  {
    id: "carthage",
    name: "Carthage",
    leader: "Hannibal",
    abilityName: "Phoenician Heritage",
    abilityDesc: "Coastal capital bonus, stronger naval movement, and mountain-crossing armies.",
    uniqueUnit: "War Elephant",
    uniqueInfra: "Cothon",
    region: "Africa",
    era: "Iron / Classical",
  },
  {
    id: "aksum",
    name: "Aksum",
    leader: "Ezana",
    abilityName: "Red Sea Trade",
    abilityDesc: "International trade routes grant extra gold and faith.",
    uniqueUnit: "Aksumite Spearman",
    uniqueInfra: "Stelae",
    region: "Africa",
    era: "Iron / Classical",
  },
  {
    id: "ethiopia_zagwe",
    name: "Ethiopia (Zagwe)",
    leader: "Lalibela",
    abilityName: "Aksumite Legacy",
    abilityDesc: "Faith from mountains and stronger combat at higher altitude.",
    uniqueUnit: "Oromo Cavalry",
    uniqueInfra: "Rock-Hewn Church",
    region: "Africa",
    era: "Medieval / Faith",
  },
  {
    id: "mali",
    name: "Mali",
    leader: "Mansa Musa",
    abilityName: "Sahel Merchants",
    abilityDesc: "+10% gold and +2 gold from each worked desert tile.",
    uniqueUnit: "Mandekalu Cavalry",
    uniqueInfra: "Suguba",
    region: "Africa",
    era: "Medieval / Faith",
  },
  {
    id: "ghana_empire",
    name: "Ghana Empire",
    leader: "Tunka Manin",
    abilityName: "Gold of Wagadu",
    abilityDesc: "Gold from mining and trade; defensive bonus in home territory.",
    uniqueUnit: "Soninke Warrior",
    uniqueInfra: "Gold Market",
    region: "Africa",
    era: "Medieval / Faith",
  },
  {
    id: "songhai",
    name: "Songhai",
    leader: "Askia",
    abilityName: "River of Gold",
    abilityDesc: "River trade yields extra gold; embarked units are stronger.",
    uniqueUnit: "Songhai Cavalry",
    uniqueInfra: "River Port",
    region: "Africa",
    era: "Medieval / Faith",
  },
  {
    id: "great_zimbabwe",
    name: "Great Zimbabwe",
    leader: "Nyatsimba",
    abilityName: "Cattle & Stone",
    abilityDesc: "Pastures generate extra gold; trade route capacity is increased.",
    uniqueUnit: "Zimbabwe Spearman",
    uniqueInfra: "Great Enclosure",
    region: "Africa",
    era: "Medieval / Faith",
  },
  {
    id: "kanem_bornu",
    name: "Kanem-Bornu",
    leader: "Idris Alooma",
    abilityName: "Trans-Saharan",
    abilityDesc: "Desert trade routes yield gold; early firearms appear in the Exploration era.",
    uniqueUnit: "Kanembu Guard",
    uniqueInfra: "Sahel Caravan Post",
    region: "Africa",
    era: "Medieval / Faith",
  },
  {
    id: "minoans",
    name: "Minoans",
    leader: "Minos",
    abilityName: "Thalassocracy",
    abilityDesc: "First naval power; coastal trade grants extra culture and gold.",
    uniqueUnit: "Minoan Bireme",
    uniqueInfra: "Labyrinth Palace",
    region: "Europe",
    era: "Bronze Age",
  },
  {
    id: "mycenaean_greece",
    name: "Mycenaean Greece",
    leader: "Agamemnon",
    abilityName: "Heroic Age",
    abilityDesc: "Heroes are cheaper to recruit; melee units gain strength during war.",
    uniqueUnit: "Mycenaean Spearman",
    uniqueInfra: "Megaron",
    region: "Europe",
    era: "Bronze Age",
  },
  {
    id: "greece",
    name: "Greece",
    leader: "Pericles",
    abilityName: "Plato's Republic",
    abilityDesc: "+20% science; melee units +2 combat strength.",
    uniqueUnit: "Hoplite",
    uniqueInfra: "Acropolis",
    region: "Europe",
    era: "Iron / Classical",
  },
  {
    id: "sparta",
    name: "Sparta",
    leader: "Leonidas",
    abilityName: "Agoge",
    abilityDesc: "Military units are cheaper and earn experience faster; defensive last-stand bonus.",
    uniqueUnit: "Spartan Hoplite",
    uniqueInfra: "Syssitia",
    region: "Europe",
    era: "Iron / Classical",
  },
  {
    id: "macedon",
    name: "Macedon",
    leader: "Alexander",
    abilityName: "Hellenistic Fusion",
    abilityDesc: "No war-weariness during conquests; capturing cities grants science and culture.",
    uniqueUnit: "Hypaspist",
    uniqueInfra: "Basilikoi Paides",
    region: "Europe",
    era: "Iron / Classical",
  },
  {
    id: "etruscans",
    name: "Etruscans",
    leader: "Lars Porsena",
    abilityName: "Twelve Cities",
    abilityDesc: "Extra trade routes and cheaper roads between cities.",
    uniqueUnit: "Etruscan Hoplite",
    uniqueInfra: "Tumulus",
    region: "Europe",
    era: "Iron / Classical",
  },
  {
    id: "rome",
    name: "Rome",
    leader: "Trajan",
    abilityName: "All Roads Lead to Rome",
    abilityDesc: "New cities are founded with a free Monument.",
    uniqueUnit: "Legionary",
    uniqueInfra: "Roman Bath",
    region: "Europe",
    era: "Iron / Classical",
  },
  {
    id: "celts_gauls",
    name: "Celts / Gauls",
    leader: "Vercingetorix",
    abilityName: "Druidic Lore",
    abilityDesc: "Faith from forests; oppida provide strong defensive positions.",
    uniqueUnit: "Gaesatae",
    uniqueInfra: "Oppidum",
    region: "Europe",
    era: "Iron / Classical",
  },
  {
    id: "byzantium",
    name: "Byzantium",
    leader: "Justinian",
    abilityName: "Taxis",
    abilityDesc: "Units gain bonus strength against civilizations of other religions.",
    uniqueUnit: "Cataphract",
    uniqueInfra: "Hippodrome",
    region: "Europe",
    era: "Medieval / Faith",
  },
  {
    id: "norse",
    name: "Norse",
    leader: "Harald Hardrada",
    abilityName: "Knarr",
    abilityDesc: "+15% gold from raiding; melee units +2 combat strength.",
    uniqueUnit: "Longship",
    uniqueInfra: "Stave Church",
    region: "Europe",
    era: "Medieval / Faith",
  },
  {
    id: "franks",
    name: "Franks",
    leader: "Charlemagne",
    abilityName: "Carolingian Reform",
    abilityDesc: "Knights appear earlier; cities generate extra faith.",
    uniqueUnit: "Frankish Paladin",
    uniqueInfra: "Palatine Chapel",
    region: "Europe",
    era: "Medieval / Faith",
  },
  {
    id: "goths",
    name: "Goths",
    leader: "Theodoric",
    abilityName: "Foederati",
    abilityDesc: "Captured units may join your forces; armies are highly mobile.",
    uniqueUnit: "Gothic Rider",
    uniqueInfra: "Wagon Fort",
    region: "Europe",
    era: "Medieval / Faith",
  },
  {
    id: "anglo_saxon_england",
    name: "Anglo-Saxon / England",
    leader: "Alfred",
    abilityName: "Workshop of the World",
    abilityDesc: "Strong production and naval supremacy; longbow defense.",
    uniqueUnit: "Longbowman",
    uniqueInfra: "Manor House",
    region: "Europe",
    era: "Medieval / Faith",
  },
  {
    id: "france",
    name: "France",
    leader: "Joan of Arc",
    abilityName: "Grand Tour",
    abilityDesc: "Wonders grant extra culture; châteaux improve tile culture output.",
    uniqueUnit: "Garde Écossaise",
    uniqueInfra: "Château",
    region: "Europe",
    era: "Medieval / Faith",
  },
  {
    id: "castile_spain",
    name: "Castile / Spain",
    leader: "Isabella",
    abilityName: "El Escorial",
    abilityDesc: "Combat bonus against other religions; treasure fleets bring gold from distant colonies.",
    uniqueUnit: "Conquistador",
    uniqueInfra: "Mission",
    region: "Europe",
    era: "Exploration",
  },
  {
    id: "portugal",
    name: "Portugal",
    leader: "Henry the Navigator",
    abilityName: "Casa da Índia",
    abilityDesc: "Long ocean trade range and increased yields from overseas trade.",
    uniqueUnit: "Nau",
    uniqueInfra: "Feitoria",
    region: "Europe",
    era: "Exploration",
  },
  {
    id: "venice",
    name: "Venice",
    leader: "Enrico Dandolo",
    abilityName: "Serenissima",
    abilityDesc: "Extra trade routes and merchant gold; settlers are replaced by city purchases.",
    uniqueUnit: "Venetian Galleass",
    uniqueInfra: "Arsenale",
    region: "Europe",
    era: "Medieval / Faith",
  },
  {
    id: "genoa",
    name: "Genoa",
    leader: "Andrea Doria",
    abilityName: "Bank of San Giorgio",
    abilityDesc: "Banking generates extra gold; mercenaries are cheaper to hire.",
    uniqueUnit: "Genoese Crossbowman",
    uniqueInfra: "Banco",
    region: "Europe",
    era: "Medieval / Faith",
  },
  {
    id: "dutch_republic",
    name: "Dutch Republic",
    leader: "William the Silent",
    abilityName: "Grachten",
    abilityDesc: "Rivers and polders boost yields; trade routes grant extra gold.",
    uniqueUnit: "Sea Beggar",
    uniqueInfra: "Polder",
    region: "Europe",
    era: "Exploration",
  },
  {
    id: "holy_roman_empire",
    name: "Holy Roman Empire / Germany",
    leader: "Barbarossa",
    abilityName: "Free Imperial Cities",
    abilityDesc: "Extra district per city and increased production.",
    uniqueUnit: "Landsknecht",
    uniqueInfra: "Hansa",
    region: "Europe",
    era: "Medieval / Faith",
  },
  {
    id: "kievan_rus",
    name: "Kievan Rus",
    leader: "Yaroslav",
    abilityName: "Lavra",
    abilityDesc: "Faith from forests and tundra; territory grows quickly.",
    uniqueUnit: "Druzhina",
    uniqueInfra: "Lavra",
    region: "Europe",
    era: "Medieval / Faith",
  },
  {
    id: "poland_lithuania",
    name: "Poland-Lithuania",
    leader: "Jadwiga",
    abilityName: "Golden Liberty",
    abilityDesc: "Culture flips conquered tiles; faith converts into culture.",
    uniqueUnit: "Winged Hussar",
    uniqueInfra: "Sukiennice",
    region: "Europe",
    era: "Medieval / Faith",
  },
  {
    id: "hungary",
    name: "Hungary",
    leader: "Matthias Corvinus",
    abilityName: "Pearl of the Danube",
    abilityDesc: "City-state levies are cheaper and stronger.",
    uniqueUnit: "Black Army",
    uniqueInfra: "Thermal Bath",
    region: "Europe",
    era: "Medieval / Faith",
  },
  {
    id: "han_china",
    name: "Han China",
    leader: "Qin Shi Huang",
    abilityName: "Dynastic Cycle",
    abilityDesc: "+15% production and +10% science.",
    uniqueUnit: "Cho-Ko-Nu",
    uniqueInfra: "Great Wall",
    region: "Asia",
    era: "Iron / Classical",
  },
  {
    id: "china_tang_song",
    name: "China (Tang/Song)",
    leader: "Taizong",
    abilityName: "Middle Kingdom",
    abilityDesc: "Capital-adjacent cities gain yields; gunpowder and printing arrive earlier.",
    uniqueUnit: "Fire Lancer",
    uniqueInfra: "Imperial Examination Hall",
    region: "Asia",
    era: "Medieval / Faith",
  },
  {
    id: "china_ming",
    name: "China (Ming)",
    leader: "Yongle",
    abilityName: "Treasure Fleets",
    abilityDesc: "Massive coastal cities; ocean trade and exploration yield extra gold.",
    uniqueUnit: "War Junk",
    uniqueInfra: "Porcelain Tower",
    region: "Asia",
    era: "Exploration",
  },
  {
    id: "maurya",
    name: "Maurya",
    leader: "Ashoka",
    abilityName: "Dharma",
    abilityDesc: "+20% food; cavalry (elephants) +2 combat strength.",
    uniqueUnit: "War Elephant",
    uniqueInfra: "Stepwell",
    region: "Asia",
    era: "Iron / Classical",
  },
  {
    id: "gupta_india",
    name: "Gupta India",
    leader: "Chandragupta II",
    abilityName: "Golden Age of India",
    abilityDesc: "Bonus science and culture; mathematics advances earlier.",
    uniqueUnit: "Gupta Elephant Archer",
    uniqueInfra: "University-Temple",
    region: "Asia",
    era: "Iron / Classical",
  },
  {
    id: "chola",
    name: "Chola",
    leader: "Rajaraja",
    abilityName: "Maritime Empire",
    abilityDesc: "Naval reach spans oceans; overseas conquest is more profitable.",
    uniqueUnit: "Chola Warship",
    uniqueInfra: "Brihadeeswara Temple",
    region: "Asia",
    era: "Medieval / Faith",
  },
  {
    id: "japan",
    name: "Japan",
    leader: "Tokugawa",
    abilityName: "Bushido",
    abilityDesc: "Units fight at full strength even when damaged; districts cluster for bonuses.",
    uniqueUnit: "Samurai",
    uniqueInfra: "Tenshu Castle",
    region: "Asia",
    era: "Medieval / Faith",
  },
  {
    id: "korea",
    name: "Korea (Goryeo/Joseon)",
    leader: "Sejong",
    abilityName: "Hwarang",
    abilityDesc: "Science from governors and mines; turtle ships bolster coastal defense.",
    uniqueUnit: "Turtle Ship",
    uniqueInfra: "Seowon",
    region: "Asia",
    era: "Medieval / Faith",
  },
  {
    id: "tibet",
    name: "Tibet",
    leader: "Songtsen Gampo",
    abilityName: "Roof of the World",
    abilityDesc: "Mountains become workable and grant faith; combat bonus at high altitude.",
    uniqueUnit: "Tibetan Cavalry",
    uniqueInfra: "Potala",
    region: "Asia",
    era: "Medieval / Faith",
  },
  {
    id: "dai_viet_vietnam",
    name: "Dai Viet (Vietnam)",
    leader: "Le Loi",
    abilityName: "Nine Dragons",
    abilityDesc: "Forest and jungle ambush bonus; strong defensive capabilities.",
    uniqueUnit: "Voi Chiến",
    uniqueInfra: "Thành",
    region: "Asia",
    era: "Medieval / Faith",
  },
  {
    id: "khmer",
    name: "Khmer",
    leader: "Jayavarman VII",
    abilityName: "Grand Barays",
    abilityDesc: "Rivers provide extra food and faith; cities can grow very large.",
    uniqueUnit: "Domrey",
    uniqueInfra: "Prasat",
    region: "Asia",
    era: "Medieval / Faith",
  },
  {
    id: "srivijaya",
    name: "Srivijaya",
    leader: "Balaputra",
    abilityName: "Maritime Mandala",
    abilityDesc: "Control of sea lanes grants trade gold; coastal cities thrive.",
    uniqueUnit: "Jong",
    uniqueInfra: "Candi",
    region: "Asia",
    era: "Medieval / Faith",
  },
  {
    id: "majapahit",
    name: "Majapahit",
    leader: "Hayam Wuruk",
    abilityName: "Nusantara",
    abilityDesc: "Bonus per coastal city; trade across islands yields extra gold.",
    uniqueUnit: "Majapahit Jong",
    uniqueInfra: "Harbor-Temple",
    region: "Asia",
    era: "Medieval / Faith",
  },
  {
    id: "pagan_burma",
    name: "Pagan (Burma)",
    leader: "Anawrahta",
    abilityName: "Land of Pagodas",
    abilityDesc: "Faith from building construction; war elephants dominate the battlefield.",
    uniqueUnit: "Burmese War Elephant",
    uniqueInfra: "Pagoda",
    region: "Asia",
    era: "Medieval / Faith",
  },
  {
    id: "ayutthaya_siam",
    name: "Ayutthaya (Siam)",
    leader: "Ramkhamhaeng",
    abilityName: "Father Governs Children",
    abilityDesc: "City-state alliances grant science, culture, and faith.",
    uniqueUnit: "Siamese War Elephant",
    uniqueInfra: "Wat",
    region: "Asia",
    era: "Medieval / Faith",
  },
  {
    id: "scythians",
    name: "Scythians",
    leader: "Tomyris",
    abilityName: "People of the Steppe",
    abilityDesc: "Extra light cavalry per build; mounted units heal after kills.",
    uniqueUnit: "Scythian Horse Archer",
    uniqueInfra: "Kurgan",
    region: "Central Asia",
    era: "Iron / Classical",
  },
  {
    id: "xiongnu",
    name: "Xiongnu",
    leader: "Modu Chanyu",
    abilityName: "Steppe Confederacy",
    abilityDesc: "Raiding yields extra gold; horse units are cheaper to produce.",
    uniqueUnit: "Xiongnu Horse Archer",
    uniqueInfra: "Felt Tent",
    region: "Central Asia",
    era: "Iron / Classical",
  },
  {
    id: "huns",
    name: "Huns",
    leader: "Attila",
    abilityName: "Scourge of God",
    abilityDesc: "Siege power from captured cities; razing cities grants production.",
    uniqueUnit: "Hunnic Horde",
    uniqueInfra: "Ordu",
    region: "Central Asia",
    era: "Medieval / Faith",
  },
  {
    id: "gokturks",
    name: "Göktürks",
    leader: "Bumin Qaghan",
    abilityName: "Sky Father",
    abilityDesc: "Cavalry gain combat strength; borders expand quickly.",
    uniqueUnit: "Turkic Lancer",
    uniqueInfra: "Stone Stele",
    region: "Central Asia",
    era: "Medieval / Faith",
  },
  {
    id: "seljuks",
    name: "Seljuks",
    leader: "Alp Arslan",
    abilityName: "Ghazi",
    abilityDesc: "Combat bonus against other religions; conquest grants faith.",
    uniqueUnit: "Ghulam",
    uniqueInfra: "Madrasa",
    region: "Central Asia",
    era: "Medieval / Faith",
  },
  {
    id: "mongols",
    name: "Mongols",
    leader: "Genghis Khan",
    abilityName: "Örtöö",
    abilityDesc: "Cavalry +1 movement and +2 combat strength.",
    uniqueUnit: "Keshig",
    uniqueInfra: "Ordu",
    region: "Central Asia",
    era: "Medieval / Faith",
  },
  {
    id: "timurids",
    name: "Timurids",
    leader: "Tamerlane",
    abilityName: "Sword of Islam",
    abilityDesc: "Siege bonus; plunder enriches cities and advances science.",
    uniqueUnit: "Timurid Siege Train",
    uniqueInfra: "Registan",
    region: "Central Asia",
    era: "Medieval / Faith",
  },
  {
    id: "ottomans",
    name: "Ottomans",
    leader: "Mehmed II",
    abilityName: "Great Bombard",
    abilityDesc: "Siege and gunpowder supremacy; conquered cities stay loyal.",
    uniqueUnit: "Janissary",
    uniqueInfra: "Grand Bazaar",
    region: "Central Asia",
    era: "Exploration",
  },
  {
    id: "olmec",
    name: "Olmec",
    leader: "Council",
    abilityName: "Mother Culture",
    abilityDesc: "Early culture and faith; colossal heads generate influence.",
    uniqueUnit: "Olmec Spearman",
    uniqueInfra: "Colossal Head",
    region: "The Americas",
    era: "Bronze Age",
  },
  {
    id: "maya",
    name: "Maya",
    leader: "Pacal the Great",
    abilityName: "Mayab",
    abilityDesc: "Cities near the capital gain yields; observatories boost science.",
    uniqueUnit: "Holkan",
    uniqueInfra: "Observatory",
    region: "The Americas",
    era: "Medieval / Faith",
  },
  {
    id: "zapotec",
    name: "Zapotec",
    leader: "Cocijo priesthood",
    abilityName: "Cloud People",
    abilityDesc: "Hill cities gain defense and extra culture.",
    uniqueUnit: "Zapotec Warrior",
    uniqueInfra: "Danzante Temple",
    region: "The Americas",
    era: "Bronze Age",
  },
  {
    id: "teotihuacan",
    name: "Teotihuacan",
    leader: "Priest-Kings",
    abilityName: "City of the Gods",
    abilityDesc: "Wonders and pyramids are cheaper; culture output is strong.",
    uniqueUnit: "Pyramid Guard",
    uniqueInfra: "Avenue of the Dead",
    region: "The Americas",
    era: "Iron / Classical",
  },
  {
    id: "toltec",
    name: "Toltec",
    leader: "Topiltzin",
    abilityName: "Toltecayotl",
    abilityDesc: "Military culture; veteran units gain extra combat strength.",
    uniqueUnit: "Toltec Warrior",
    uniqueInfra: "Atlantean Hall",
    region: "The Americas",
    era: "Medieval / Faith",
  },
  {
    id: "aztec",
    name: "Aztec",
    leader: "Montezuma",
    abilityName: "Legend of the Eagle",
    abilityDesc: "Melee units +3 combat strength.",
    uniqueUnit: "Eagle Warrior",
    uniqueInfra: "Tlachtli",
    region: "The Americas",
    era: "Medieval / Faith",
  },
  {
    id: "inca",
    name: "Inca",
    leader: "Pachacuti",
    abilityName: "Mit'a",
    abilityDesc: "Mountains become workable; terrace farms feed large cities.",
    uniqueUnit: "Warak'aq",
    uniqueInfra: "Terrace Farm",
    region: "The Americas",
    era: "Medieval / Faith",
  },
  {
    id: "muisca",
    name: "Muisca",
    leader: "Zipa",
    abilityName: "El Dorado",
    abilityDesc: "Faith converts into gold; lake and highland tiles yield more.",
    uniqueUnit: "Guecha Warrior",
    uniqueInfra: "Salt Temple",
    region: "The Americas",
    era: "Medieval / Faith",
  },
  {
    id: "mississippian_cahokia",
    name: "Mississippian (Cahokia)",
    leader: "Great Sun",
    abilityName: "Mound Builders",
    abilityDesc: "Earthwork improvements generate culture and faith; river trade is strong.",
    uniqueUnit: "Cahokian Warrior",
    uniqueInfra: "Earthwork Mound",
    region: "The Americas",
    era: "Medieval / Faith",
  },
  {
    id: "haudenosaunee",
    name: "Haudenosaunee (Iroquois)",
    leader: "Hiawatha",
    abilityName: "Great League",
    abilityDesc: "Forest movement and combat bonus; longhouses boost production.",
    uniqueUnit: "Mohawk Warrior",
    uniqueInfra: "Longhouse",
    region: "The Americas",
    era: "Medieval / Faith",
  },
  {
    id: "pueblo",
    name: "Pueblo",
    leader: "Council",
    abilityName: "Cliff Dwellers",
    abilityDesc: "Desert and mesa tiles grant defense and extra housing.",
    uniqueUnit: "Pueblo Skirmisher",
    uniqueInfra: "Cliff Palace",
    region: "The Americas",
    era: "Medieval / Faith",
  },
  {
    id: "polynesia",
    name: "Polynesia",
    leader: "Hotu Matua",
    abilityName: "Wayfinding",
    abilityDesc: "Ocean embark and sight from the start; settle distant islands early.",
    uniqueUnit: "Koa Warrior",
    uniqueInfra: "Marae",
    region: "Oceania",
    era: "Medieval / Faith",
  },
  {
    id: "maori",
    name: "Māori",
    leader: "Kupe",
    abilityName: "Mana",
    abilityDesc: "Start at sea; unimproved forests and reefs grant yields; pā defend strongly.",
    uniqueUnit: "Toa",
    uniqueInfra: "Pā",
    region: "Oceania",
    era: "Medieval / Faith",
  },
  {
    id: "hawaii",
    name: "Hawaiʻi",
    leader: "Kamehameha",
    abilityName: "Aloha ʻĀina",
    abilityDesc: "Coastal cities gain amenities; island unification yields extra gold.",
    uniqueUnit: "Hawaiian Koa",
    uniqueInfra: "Heiau",
    region: "Oceania",
    era: "Medieval / Faith",
  },

  // ---- Expansion roster ----------------------------------------------------
  { id: "arabia", name: "Arabia", leader: "Harun al-Rashid", abilityName: "Faith of the Prophet", abilityDesc: "International trade routes grant faith and science; conquered cities settle quickly.", uniqueUnit: "Camel Archer", uniqueInfra: "House of Wisdom", region: "Mesopotamia & Near East", era: "Medieval / Faith" },
  { id: "israelites", name: "Israelites", leader: "Solomon", abilityName: "Kingdom of David", abilityDesc: "Faster wonder production in the capital; faith from trade routes.", uniqueUnit: "Gibborim", uniqueInfra: "First Temple", region: "Mesopotamia & Near East", era: "Iron / Classical" },
  { id: "nabataeans", name: "Nabataeans", leader: "Aretas IV", abilityName: "Incense Road", abilityDesc: "Extra gold from worked desert tiles; desert cities gain food from cisterns.", uniqueUnit: "Desert Raider", uniqueInfra: "Cistern", region: "Mesopotamia & Near East", era: "Iron / Classical" },
  { id: "saba", name: "Saba", leader: "Bilqis", abilityName: "Frankincense Kingdom", abilityDesc: "Luxury and gold wealth; dam irrigation grants food on fresh water.", uniqueUnit: "Sabaean Spearman", uniqueInfra: "Marib Dam", region: "Mesopotamia & Near East", era: "Iron / Classical" },
  { id: "mitanni", name: "Mitanni", leader: "Tushratta", abilityName: "Maryannu", abilityDesc: "Chariots and mounted units fight harder; horse breeding tradition.", uniqueUnit: "Maryannu Chariot", uniqueInfra: "Kikkuli Stables", region: "Mesopotamia & Near East", era: "Bronze Age" },
  { id: "urartu", name: "Urartu", leader: "Sarduri II", abilityName: "Kingdom of Van", abilityDesc: "Mining production; strong defensive buildings in the highlands.", uniqueUnit: "Urartian Charioteer", uniqueInfra: "Fortress of Van", region: "Mesopotamia & Near East", era: "Iron / Classical" },
  { id: "greco_bactria", name: "Greco-Bactria", leader: "Demetrius I", abilityName: "Thousand Cities", abilityDesc: "Hellenistic fusion: extra science and culture in every city.", uniqueUnit: "Bactrian Cataphract", uniqueInfra: "Gymnasion", region: "Persia & Iran", era: "Iron / Classical" },
  { id: "sogdia", name: "Sogdia", leader: "Divashtich", abilityName: "Lords of the Silk Road", abilityDesc: "Greater trade-route gold and capacity.", uniqueUnit: "Sogdian Cavalry", uniqueInfra: "Caravanserai", region: "Persia & Iran", era: "Medieval / Faith" },
  { id: "khwarazm", name: "Khwarazm", leader: "Ala ad-Din Muhammad II", abilityName: "Shahs of Khwarazm", abilityDesc: "Gold from trade, but a sprawling army costs more to maintain.", uniqueUnit: "Khwarazmian Lancer", uniqueInfra: "Gurganj Bazaar", region: "Persia & Iran", era: "Medieval / Faith" },
  { id: "numidia", name: "Numidia", leader: "Masinissa", abilityName: "Masaesyli Horse", abilityDesc: "Light cavalry move farther and heal on the move.", uniqueUnit: "Numidian Cavalry", uniqueInfra: "Royal Horse Market", region: "Africa", era: "Iron / Classical" },
  { id: "fatimids", name: "Fatimid Caliphate", leader: "al-Mu'izz", abilityName: "Isma'ili Caliphate", abilityDesc: "Extra science and faith; gold from Mediterranean trade.", uniqueUnit: "Fatimid Ghulam", uniqueInfra: "Al-Azhar", region: "Africa", era: "Medieval / Faith" },
  { id: "ayyubids", name: "Ayyubids", leader: "Saladin", abilityName: "Sultan of Egypt & Syria", abilityDesc: "Units fight harder and heal in home territory.", uniqueUnit: "Ayyubid Faris", uniqueInfra: "Citadel of Cairo", region: "Africa", era: "Medieval / Faith" },
  { id: "mamluks", name: "Mamluk Sultanate", leader: "Baybars", abilityName: "Slave Soldiers", abilityDesc: "Elite cavalry bought with gold; mounted units fight harder.", uniqueUnit: "Mamluk", uniqueInfra: "Maydan", region: "Africa", era: "Medieval / Faith" },
  { id: "almoravids", name: "Almoravids", leader: "Yusuf ibn Tashfin", abilityName: "Veiled Sultanate", abilityDesc: "Trans-Saharan gold; faith fuels the melee line.", uniqueUnit: "Lamtuna Spearman", uniqueInfra: "Ribat", region: "Africa", era: "Medieval / Faith" },
  { id: "swahili", name: "Swahili (Kilwa)", leader: "al-Hasan ibn Sulaiman", abilityName: "Monsoon Trade", abilityDesc: "Large coastal-city gold and international trade-route gold.", uniqueUnit: "Swahili Dhow", uniqueInfra: "Husuni Kubwa", region: "Africa", era: "Medieval / Faith" },
  { id: "benin", name: "Benin", leader: "Oba Ewuare", abilityName: "Walls of Benin", abilityDesc: "Earthwork defenses and bronze-casting culture.", uniqueUnit: "Ogboni Guard", uniqueInfra: "Iya Earthworks", region: "Africa", era: "Medieval / Faith" },
  { id: "kongo", name: "Kongo", leader: "Afonso I", abilityName: "Kingdom of Kongo", abilityDesc: "Faith and culture from conversion; nkutu cloth trade.", uniqueUnit: "Kongo Archer", uniqueInfra: "Mbanza", region: "Africa", era: "Exploration" },
  { id: "bulgaria", name: "Bulgaria", leader: "Krum", abilityName: "Khans of the Danube", abilityDesc: "Cavalry fight harder; captured cities keep more population.", uniqueUnit: "Bulgar Horse Archer", uniqueInfra: "Preslav Court", region: "Europe", era: "Medieval / Faith" },
  { id: "serbia", name: "Serbia", leader: "Stefan Dušan", abilityName: "Dušan's Code", abilityDesc: "Culture from law; silver mining gold.", uniqueUnit: "Pronoia Knight", uniqueInfra: "Despot's Hall", region: "Europe", era: "Medieval / Faith" },
  { id: "bohemia", name: "Bohemia", leader: "Charles IV", abilityName: "Crown of St. Wenceslas", abilityDesc: "Silver mining gold; universities grant extra science.", uniqueUnit: "Hussite War Wagon", uniqueInfra: "Kutná Hora Mint", region: "Europe", era: "Medieval / Faith" },
  { id: "swiss", name: "Swiss Confederacy", leader: "Werner Stauffacher", abilityName: "Reisläufer", abilityDesc: "Elite pikemen and mercenaries; strong mountain defense.", uniqueUnit: "Swiss Halberdier", uniqueInfra: "Rütli Meadow", region: "Europe", era: "Medieval / Faith" },
  { id: "aragon", name: "Crown of Aragon", leader: "James I", abilityName: "Mare Nostrum", abilityDesc: "Naval power and coastal-trade gold; Almogavar raiders.", uniqueUnit: "Almogàver", uniqueInfra: "Llotja", region: "Europe", era: "Medieval / Faith" },
  { id: "scotland", name: "Scotland", leader: "Robert the Bruce", abilityName: "Schiltron", abilityDesc: "Anti-cavalry spears; faith from the highlands.", uniqueUnit: "Highland Schiltron", uniqueInfra: "Tower House", region: "Europe", era: "Medieval / Faith" },
  { id: "gaelic_ireland", name: "Gaelic Ireland", leader: "Brian Boru", abilityName: "High Kingship", abilityDesc: "Monastic faith and culture; galloglass mercenaries.", uniqueUnit: "Gallowglass", uniqueInfra: "Round Tower", region: "Europe", era: "Medieval / Faith" },
  { id: "normans", name: "Normans (Sicily)", leader: "Roger II", abilityName: "Hauteville Conquest", abilityDesc: "Strong knights and multicultural administration (gold & science).", uniqueUnit: "Norman Knight", uniqueInfra: "Palatine Chapel", region: "Europe", era: "Medieval / Faith" },
  { id: "visigoths", name: "Visigoths", leader: "Leovigild", abilityName: "Kingdom of Toledo", abilityDesc: "Captured cities keep population; a law code grants culture.", uniqueUnit: "Visigothic Noble", uniqueInfra: "Hall of Toledo", region: "Europe", era: "Medieval / Faith" },
  { id: "novgorod", name: "Novgorod", leader: "Alexander Nevsky", abilityName: "Fur Republic", abilityDesc: "Gold from northern coastal and forest trade.", uniqueUnit: "Ushkuinik", uniqueInfra: "Veche Bell", region: "Europe", era: "Medieval / Faith" },
  { id: "illyrians", name: "Illyrians", leader: "Teuta", abilityName: "Adriatic Pirates", abilityDesc: "Coastal raiding gold and faster ships.", uniqueUnit: "Liburnian", uniqueInfra: "Gradina", region: "Europe", era: "Iron / Classical" },
  { id: "lusitani", name: "Lusitani", leader: "Viriathus", abilityName: "Concursare", abilityDesc: "Units fight harder in forest and rough terrain (hit-and-run).", uniqueUnit: "Falcata Warrior", uniqueInfra: "Castro", region: "Europe", era: "Iron / Classical" },
  { id: "arevaci", name: "Arevaci", leader: "Caros", abilityName: "Spirit of Numantia", abilityDesc: "Celtiberian steel and tenacious fortress defense.", uniqueUnit: "Celtiberian Warrior", uniqueInfra: "Murallas de Numancia", region: "Europe", era: "Iron / Classical" },
  { id: "thracians", name: "Thracians", leader: "Sitalces", abilityName: "Odrysian Host", abilityDesc: "Superior light infantry; a mercenary skirmisher tradition.", uniqueUnit: "Thracian Peltast", uniqueInfra: "Thracian Tomb", region: "Europe", era: "Iron / Classical" },
  { id: "dacians", name: "Dacians", leader: "Decebalus", abilityName: "Gold of the Carpathians", abilityDesc: "Gold and production from mountain mines; the armor-cleaving falx.", uniqueUnit: "Falxman", uniqueInfra: "Murus Dacicus", region: "Europe", era: "Iron / Classical" },
  { id: "sami", name: "Sámi", leader: "Noaidi Council", abilityName: "People of the Eight Seasons", abilityDesc: "Faith and food from the far north; at home in snow and tundra.", uniqueUnit: "Ski Raider", uniqueInfra: "Siida Camp", region: "Europe", era: "Medieval / Faith" },
  { id: "corinth", name: "Corinth", leader: "Periander", abilityName: "Two Seas", abilityDesc: "A commerce hub: trade-route and coastal-city gold.", uniqueUnit: "Corinthian Trireme", uniqueInfra: "Diolkos", region: "Europe", era: "Iron / Classical" },
  { id: "thebes", name: "Thebes", leader: "Epaminondas", abilityName: "Sacred Band", abilityDesc: "Elite heavy infantry with oblique-order flanking.", uniqueUnit: "Sacred Band", uniqueInfra: "Cadmea", region: "Europe", era: "Iron / Classical" },
  { id: "eretria", name: "Eretria", leader: "Eretrian Assembly", abilityName: "Euboean Colonists", abilityDesc: "New cities start larger; the alphabet and trade spread culture and gold.", uniqueUnit: "Penteconter", uniqueInfra: "Emporion", region: "Europe", era: "Iron / Classical" },
  { id: "crete", name: "Crete", leader: "Nearchus", abilityName: "Cretan Archers", abilityDesc: "Ranged units gain range and strength (the era's best mercenary archers).", uniqueUnit: "Cretan Archer", uniqueInfra: "Gortyn Code", region: "Europe", era: "Iron / Classical" },
  { id: "indus_valley", name: "Indus Valley", leader: "Priest-Council", abilityName: "Planned Cities", abilityDesc: "New cities start larger with a free Granary; sanitation feeds growth.", uniqueUnit: "Harappan Spearman", uniqueInfra: "Great Bath", region: "Asia", era: "Bronze Age" },
  { id: "zhou_china", name: "Zhou China", leader: "King Wu", abilityName: "Mandate of Heaven", abilityDesc: "Culture and faith of legitimacy; feudal levies.", uniqueUnit: "Zhou Chariot", uniqueInfra: "Ancestral Temple", region: "Asia", era: "Bronze Age" },
  { id: "delhi_sultanate", name: "Delhi Sultanate", leader: "Alauddin Khalji", abilityName: "Sultanate of Hind", abilityDesc: "Price controls grant gold and food.", uniqueUnit: "Delhi War Elephant", uniqueInfra: "Hauz", region: "Asia", era: "Medieval / Faith" },
  { id: "mughals", name: "Mughal Empire", leader: "Akbar", abilityName: "Padishah", abilityDesc: "Wonders and culture flourish under religious tolerance.", uniqueUnit: "Mughal Sowar", uniqueInfra: "Red Fort", region: "Asia", era: "Exploration" },
  { id: "vijayanagara", name: "Vijayanagara", leader: "Krishnadevaraya", abilityName: "City of Victory", abilityDesc: "Temple-bazaar gold and faith; tank-fed farmland.", uniqueUnit: "Vijayanagara War Elephant", uniqueInfra: "Temple Tank", region: "Asia", era: "Exploration" },
  { id: "champa", name: "Champa", leader: "Jaya Indravarman IV", abilityName: "Lords of the Sea", abilityDesc: "Coastal raiding gold and a swift navy.", uniqueUnit: "Cham Raider", uniqueInfra: "My Son Tower", region: "Asia", era: "Medieval / Faith" },
  { id: "sinhala", name: "Sinhala", leader: "Parakramabahu I", abilityName: "Let No Drop Waste", abilityDesc: "Tank irrigation grants food and production from fresh water.", uniqueUnit: "Sinhala War Elephant", uniqueInfra: "Wewa", region: "Asia", era: "Medieval / Faith" },
  { id: "khitan", name: "Khitan (Liao)", leader: "Abaoji", abilityName: "Dual Administration", abilityDesc: "Mobile cavalry and productive cities (steppe and sown).", uniqueUnit: "Ordo Cavalry", uniqueInfra: "Ordo Camp", region: "Asia", era: "Medieval / Faith" },
  { id: "jurchen", name: "Jurchen (Jin)", leader: "Aguda", abilityName: "Meng'an-Mouke", abilityDesc: "Heavy cavalry militia skilled at storming cities.", uniqueUnit: "Iron Pagoda", uniqueInfra: "Meng'an Garrison", region: "Asia", era: "Medieval / Faith" },
  { id: "khazars", name: "Khazars", leader: "Bulan", abilityName: "Toll of the Steppe", abilityDesc: "Trade-route gold and tolerant faith.", uniqueUnit: "Khazar Lancer", uniqueInfra: "Sarkel Fortress", region: "Central Asia", era: "Medieval / Faith" },
  { id: "avars", name: "Avars", leader: "Bayan I", abilityName: "Ring of the Avars", abilityDesc: "Stirrup cavalry combat and tribute gold from raids.", uniqueUnit: "Avar Lancer", uniqueInfra: "Hring", region: "Central Asia", era: "Medieval / Faith" },
  { id: "golden_horde", name: "Golden Horde", leader: "Batu Khan", abilityName: "Tatar Yoke", abilityDesc: "Tribute gold from raids; swift horse archers.", uniqueUnit: "Tatar Horse Archer", uniqueInfra: "Yam Relay", region: "Central Asia", era: "Medieval / Faith" },
  { id: "chimu", name: "Chimú", leader: "Minchançaman", abilityName: "Kingdom of Chimor", abilityDesc: "Coastal-desert irrigation feeds cities; goldsmith luxury gold.", uniqueUnit: "Chimú Slinger", uniqueInfra: "Chan Chan Citadel", region: "The Americas", era: "Medieval / Faith" },
  { id: "moche", name: "Moche", leader: "Lord of Sipán", abilityName: "Huaca Builders", abilityDesc: "Adobe pyramids give faith and culture.", uniqueUnit: "Moche Warrior", uniqueInfra: "Huaca", region: "The Americas", era: "Iron / Classical" },
  { id: "tiwanaku", name: "Tiwanaku", leader: "Priest-Rulers", abilityName: "Raised Fields", abilityDesc: "Highland and lake farming; faith from monoliths.", uniqueUnit: "Tiwanaku Spearman", uniqueInfra: "Akapana Pyramid", region: "The Americas", era: "Iron / Classical" },
  { id: "tarascans", name: "Tarascans", leader: "Tariácuri", abilityName: "Metalsmiths of Michoacán", abilityDesc: "Copper and bronze metallurgy boost production and combat.", uniqueUnit: "Copper Macehead", uniqueInfra: "Yácata", region: "The Americas", era: "Exploration" },
  { id: "taino", name: "Taíno", leader: "Anacaona", abilityName: "Caciquedom", abilityDesc: "Island culture and faith; cassava feeds the people.", uniqueUnit: "Guaribo Slinger", uniqueInfra: "Batey", region: "The Americas", era: "Exploration" },
  { id: "tonga", name: "Tonga", leader: "Tuʻi Tonga", abilityName: "Maritime Tribute", abilityDesc: "Gold and faith from coastal and island cities; long voyaging.", uniqueUnit: "Tongan Toa", uniqueInfra: "Langi", region: "Oceania", era: "Medieval / Faith" },
];

export const PILLARS = [
  {
    title: 'Explore',
    desc: 'Chart unknown lands, dispatch scouts, and reveal resources from wheat fields to iron mines.',
    image: 'pillar_explore',
  },
  {
    title: 'Expand',
    desc: 'Found cities across continents, claim territory, and build roads that bind your empire together.',
    image: 'pillar_expand',
  },
  {
    title: 'Exploit',
    desc: 'Assign citizens, improve tiles, trade luxuries, and balance food, production, gold, and science.',
    image: 'pillar_exploit',
  },
  {
    title: 'Exterminate',
    desc: 'Wage tactical wars with unique units, promotions, and combined-arms combat across land and sea.',
    image: 'pillar_exterminate',
  },
] as const;

export const ERAS = [
  { name: 'Stone / Dawn', years: '4000–3000 BCE', desc: 'First tribes, farms, and mud-brick cities.', image: 'age_stone_dawn' },
  { name: 'Bronze Age', years: '3000–1200 BCE', desc: 'Chariots, ziggurats, and the first empires.', image: 'age_bronze' },
  { name: 'Iron / Classical', years: '1200 BCE–500 CE', desc: 'Legions, phalanxes, philosophy, and great roads.', image: 'age_iron_classical' },
  { name: 'Medieval / Faith', years: '500–1300 CE', desc: 'Knights, castles, samurai, and cathedrals.', image: 'age_medieval' },
  { name: 'Exploration', years: '1300–1550 CE', desc: 'Caravels, gunpowder, printing, and global trade.', image: 'age_exploration' },
] as const;

export const HERO_IMAGES = [
  'hero_ancient_empire',
  'hero_battlefield',
  'hero_maritime_trade',
] as const;

export const ALL_LEADERS = [
  'akkad', 'aksum', 'anglo_saxon_england', 'assyria', 'ayutthaya_siam', 'aztec', 'babylon', 'byzantium',
  'carthage', 'castile_spain', 'celts_gauls', 'china_ming', 'china_tang_song', 'chola', 'dai_viet_vietnam',
  'dutch_republic', 'egypt', 'elam', 'ethiopia_zagwe', 'etruscans', 'france', 'franks', 'genoa',
  'ghana_empire', 'gokturks', 'goths', 'great_zimbabwe', 'greece', 'gupta_india', 'han_china', 'haudenosaunee',
  'hawaii', 'hittites', 'holy_roman_empire', 'hungary', 'huns', 'inca', 'japan', 'kanem_bornu', 'khmer',
  'kievan_rus', 'korea', 'kush_nubia', 'lydia', 'macedon', 'majapahit', 'mali', 'maori', 'maurya', 'maya',
  'median_empire', 'minoans', 'mississippian_cahokia', 'mongols', 'muisca', 'mycenaean_greece', 'norse',
  'olmec', 'ottomans', 'pagan_burma', 'parthia', 'persia', 'phoenicia', 'poland_lithuania', 'polynesia',
  'portugal', 'pueblo', 'rome', 'sassanid_persia', 'scythians', 'seljuks', 'songhai', 'sparta', 'srivijaya',
  'sumer', 'teotihuacan', 'tibet', 'timurids', 'toltec', 'venice', 'xiongnu', 'zapotec',
  // expansion roster
  'arabia', 'israelites', 'nabataeans', 'saba', 'mitanni', 'urartu', 'greco_bactria', 'sogdia', 'khwarazm',
  'numidia', 'fatimids', 'ayyubids', 'mamluks', 'almoravids', 'swahili', 'benin', 'kongo', 'bulgaria',
  'serbia', 'bohemia', 'swiss', 'aragon', 'scotland', 'gaelic_ireland', 'normans', 'visigoths', 'novgorod',
  'illyrians', 'lusitani', 'arevaci', 'thracians', 'dacians', 'sami', 'corinth', 'thebes', 'eretria', 'crete',
  'indus_valley', 'zhou_china', 'delhi_sultanate', 'mughals', 'vijayanagara', 'champa', 'sinhala', 'khitan',
  'jurchen', 'khazars', 'avars', 'golden_horde', 'chimu', 'moche', 'tiwanaku', 'tarascans', 'taino', 'tonga',
];
