// Emoji → generated-icon bridge.
//
// The whole app is authored with emoji (🪙, ⚔, 🔬 …). This module swaps each one
// for a hand-painted PNG generated by the art pipeline (see tools/art-generator,
// `bun run generate-icons`, output copied to public/icons/<id>.png).
//
// It is deliberately turnkey and self-healing:
//  • Until the PNGs exist it is a no-op — `iconify()` returns the original HTML
//    (emoji), and canvas draws fall back to `fillText`. So nothing breaks now.
//  • A tiny probe loads one sentinel icon; the moment the generated set is dropped
//    into public/icons the whole UI upgrades to icons on the next render — no code
//    change needed.
//  • Any individual icon that 404s falls back to its emoji via `onerror`.
//
// DOM usage: wrap HTML you assign to innerHTML with `iconify(html)` (tag-aware, so
// it never touches emoji inside attributes). Canvas usage: `drawGlyph(ctx, …)`.

import { ASSET_BASE_URL } from "./asset-base";

/** Emoji → icon id. Ids match tools/art-generator/config.ts EMOJI_ICON_DEFS and
 *  the files at public/icons/<id>.png. */
export const EMOJI_ICON: Record<string, string> = {
  "🪙": "ic_gold", "⚔": "ic_war", "☮": "ic_peace_symbol", "🔬": "ic_science",
  "🏛": "ic_temple", "⚒": "ic_production", "🎭": "ic_culture", "🏆": "ic_trophy",
  "★": "ic_star_outline", "🍞": "ic_food", "🕊": "ic_dove", "🤝": "ic_handshake",
  "🏙": "ic_city", "⚙": "ic_gear", "🛠": "ic_tools", "📜": "ic_scroll",
  "🔒": "ic_lock", "📖": "ic_book", "🗺": "ic_map", "🛡": "ic_shield",
  "⚠": "ic_warning", "🎖": "ic_medal", "🐪": "ic_dromedary", "🪖": "ic_helmet",
  "👑": "ic_crown", "⚡": "ic_bolt", "👥": "ic_population", "☰": "ic_menu",
  "🎌": "ic_festival", "👷": "ic_worker", "⭐": "ic_star", "✨": "ic_sparkles",
  "🍷": "ic_wine", "🚪": "ic_door", "📨": "ic_envelope", "🌾": "ic_wheat",
  "💤": "ic_sleep", "📍": "ic_pin", "🐫": "ic_bactrian", "⏱": "ic_stopwatch",
  "⛪": "ic_church", "🏹": "ic_bow", "🥾": "ic_boot", "⏳": "ic_hourglass",
  "🏠": "ic_house", "🌲": "ic_pine", "↔": "ic_arrows_lr", "🙏": "ic_pray",
  "🖐": "ic_hand", "🔥": "ic_fire", "🐞": "ic_bug", "⏸": "ic_pause",
  "✝": "ic_cross", "❤": "ic_heart", "❗": "ic_exclaim", "📢": "ic_megaphone",
  "🎁": "ic_gift", "📤": "ic_outbox", "📥": "ic_inbox", "🛣": "ic_road",
  "🎲": "ic_die", "📂": "ic_folder", "🧱": "ic_brick", "🛤": "ic_rail",
  "♜": "ic_rook", "⛏": "ic_pickaxe", "◀": "ic_tri_left", "▶": "ic_tri_right",
  "💾": "ic_save", "🌳": "ic_tree", "♻": "ic_recycle", "⬆": "ic_arrow_up",
  "🔓": "ic_unlock", "☠": "ic_skull", "⚓": "ic_anchor", "🏃": "ic_runner",
  "⚑": "ic_flag", "🔫": "ic_musket", "🔄": "ic_refresh", "☩": "ic_cross_ornate",
  "😊": "ic_smile", "😟": "ic_frown", "🔨": "ic_hammer", "👁": "ic_eye",
};

const iconUrl = (id: string): string => `${ASSET_BASE_URL}icons/${id}.png`;

// --- availability probe: off until the generated set is present -------------
let enabled = false;
if (typeof Image !== "undefined") {
  const probe = new Image();
  probe.onload = () => { enabled = true; };
  probe.src = iconUrl("ic_gold"); // sentinel — if this exists the whole set does
}

/** For tests / callers that want to force icon rendering on. */
export function setIconsEnabled(on: boolean): void { enabled = on; }
export function iconsEnabled(): boolean { return enabled; }

// A regex matching any known emoji, allowing a trailing VS16 (U+FE0F) that some
// source/platforms append. Longest keys first so multi-codepoint emoji win.
const escape = (s: string): string => s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
const EMOJI_RE = new RegExp(
  "(" + Object.keys(EMOJI_ICON).sort((a, b) => b.length - a.length).map(escape).join("|") + ")\\uFE0F?",
  "gu",
);

/** Replace known emoji in a plain-text fragment with <img> icons. */
function iconifyText(text: string): string {
  return text.replace(EMOJI_RE, (m) => {
    const id = EMOJI_ICON[m.replace(/️/g, "")];
    if (!id) return m;
    // alt carries the emoji so onerror can restore it if the PNG is missing.
    return `<img class="gi" src="${iconUrl(id)}" alt="${m}" draggable="false" ` +
      `onerror="this.replaceWith(document.createTextNode(this.getAttribute('alt')))">`;
  });
}

/**
 * Swap emoji for icons in an HTML string, safely: the string is split into tags
 * and text runs and only the text runs are transformed, so emoji sitting inside
 * an attribute value are never touched. A no-op until the icon set is present.
 */
export function iconify(html: string): string {
  if (!enabled || !html) return html;
  // Even indices are text, odd indices are whole tags (<...>).
  return html.split(/(<[^>]*>)/).map((seg, i) => (i % 2 === 1 ? seg : iconifyText(seg))).join("");
}

// --- canvas -----------------------------------------------------------------
const imgCache = new Map<string, HTMLImageElement>();

/** A loaded icon Image for an emoji, or null if unavailable/not yet loaded. */
function iconImage(glyph: string): HTMLImageElement | null {
  if (!enabled || typeof Image === "undefined") return null;
  const id = EMOJI_ICON[glyph.replace(/️/g, "")];
  if (!id) return null;
  let img = imgCache.get(id);
  if (!img) {
    img = new Image();
    img.src = iconUrl(id);
    imgCache.set(id, img);
  }
  return img.complete && img.naturalWidth > 0 ? img : null;
}

/**
 * Draw a glyph on the canvas: if it's a known emoji and its icon is ready, draw
 * the icon centered at (x,y) at `size`px; otherwise fall back to `fillText`
 * (honoring the caller's current textAlign/textBaseline). Returns nothing.
 */
export function drawGlyph(
  ctx: CanvasRenderingContext2D,
  glyph: string,
  x: number,
  y: number,
  size: number,
): void {
  const img = iconImage(glyph);
  if (img) ctx.drawImage(img, x - size / 2, y - size / 2, size, size);
  else ctx.fillText(glyph, x, y);
}

// --- one-time CSS for inline DOM icons --------------------------------------
if (typeof document !== "undefined") {
  const style = document.createElement("style");
  style.textContent =
    ".gi{display:inline-block;width:1em;height:1em;vertical-align:-0.14em;object-fit:contain;" +
    "image-rendering:auto}";
  document.head.appendChild(style);
}

// --- whole-app DOM hook -----------------------------------------------------
// Rather than wrapping ~90 individual `el.innerHTML = …` sites, we patch the
// innerHTML setter once so every HTML string the app assigns is run through the
// (tag-safe, probe-gated) iconify. The getter is untouched, so escapeHtml-style
// read-backs are unaffected; onerror uses replaceWith (never innerHTML), so there
// is no recursion. A no-op until the generated icon set is present.
let hooked = false;
export function installIconifyHook(): void {
  if (hooked || typeof Element === "undefined") return;
  const desc = Object.getOwnPropertyDescriptor(Element.prototype, "innerHTML");
  if (!desc?.set || !desc.get) return;
  const origSet = desc.set;
  Object.defineProperty(Element.prototype, "innerHTML", {
    configurable: true,
    enumerable: desc.enumerable,
    get: desc.get,
    set(this: Element, value: unknown) {
      origSet.call(this, typeof value === "string" ? iconify(value) : value);
    },
  });
  hooked = true;
}
