/** Every coach step, in narration order. Shared by coach voice and the runtime coach. */
export const TUTORIAL_STEP_IDS = [
  "t1_intro",
  "t1_select_scout",
  "t1_unit_stats",
  "t1_unit_kinds",
  "t1_move_scout",
  "t1_select_warrior",
  "t1_move_warrior",
  "t1_select_settler",
  "t1_found_city",
  "t1_yields",
  "t1_open_research",
  "t1_pick_research",
  "t1_select_city",
  "t1_open_construction",
  "t1_pick_build",
  "t1_open_train",
  "t1_train_unit",
  "t1_next_button",
  "t1_end_turn",
  "spot_barbarian",
  "spot_enemy",
  "t2_check_city",
  "t2_combat_brief",
  "t2_attack_barbarian",
  "t2_victory",
  "t2_end_turn",
  "t3_village",
  "t3_end_turn",
  "t4_diplomacy",
  "t4_end_turn",
  "t5_wrap_up",
  "t5_choice",
  "complete",
] as const;

export type TutorialStepId = (typeof TUTORIAL_STEP_IDS)[number];
