// NorthAmerica regional land mask — baked from Natural Earth via tools/geodata-poc/bake-regional-mask.mjs.
import { createRegionalMask } from "./regional-mask";

export const NORTH_AMERICA_LON_MIN = -168;
export const NORTH_AMERICA_LON_MAX = -52;
export const NORTH_AMERICA_LAT_MIN = 12;
export const NORTH_AMERICA_LAT_MAX = 72;
export const NORTH_AMERICA_MASK_COLS = 116;
export const NORTH_AMERICA_MASK_ROWS = 64;

const northAmericaMask = createRegionalMask({
  lonMin: NORTH_AMERICA_LON_MIN,
  lonMax: NORTH_AMERICA_LON_MAX,
  latMin: NORTH_AMERICA_LAT_MIN,
  latMax: NORTH_AMERICA_LAT_MAX,
  maskCols: NORTH_AMERICA_MASK_COLS,
  maskRows: NORTH_AMERICA_MASK_ROWS,
  maskB64:
    "AAAAAABw7P8gx/+/AAAL8AcAAACA/B9w+P9vAGDg//8H0Gv4/0EOuPEPAO7///////89I87NA34AAPj//////x/yuf8+mL8ABPz//////3//9/8B+D+A/v//////////3wPAjwPo////////////7+D/AYCA//////////97bIB/AID///////////8BAOAGAPz//////////wcAfSAAwP/f////////HwDADwAA2n+O////////AQD8AwAA/BEA//////8fAMA/DAAAvACA//////8HAPzvAQBABgDg/////38AgP8fAAAjAAD0//////8A+P8DAAYAAMD//////z/A/38AGAAAAMD//////z///z8AAAAAgPr///////H/fwMAAAAAAP//////P/7//wAAAAAA8P//////5///BwAAAAAA/v////////+fAAAAAACw/////////wEMAAAAAADs////////58ADAAAAAID+////////AX8AAAAAAPD///////99AAUAAAAAAP////////9XAAAAAAAA8P///////z8HAAAAAACA////////fwYAAAAAAADw////////AwAAAAAAAID///////8fAAAAAAAAAPD///////8BAAAAAAAAgP///////wMAAAAAAAAA8P//////LwAAAAAAAAAA////////AAAAAAAAAADA//////8PAAAAAAAAAAD8//////8AAAAAAAAAAID//////w8AAAAAAAAAAPj/////fwAAAAAAAAAAAP7/////AwAAAAAAAAAAwP////8PAAAAAAAAAAAA+P///38AAAAAAAAAAACA/f///wMAAAAAAAAAAACQ//9/fAAAAAAAAAAAAAD6/x8BAwAAAAAAAAAAAED//wBgAAAAAAAAAAAAAOb/AwAGAAAAAAAAAAAAgPl/AMAAAAAAAAAAAAAAiP8DAAQAAAAAAAAAAAAA8T8AAAAAAAAAAAAAAAAg/gMAAAAAAAAAAAAAAADAPwDwAAAAAAAAAAAAAAD8AwA5AAAAAAgAAAAAAIB/wAEMAAAAAAAAAAAAAPwHDkABAAAAAAAAAAAAAP/gAIAHAAAAAAAAAAAA4P8HQAADAAAAAAAAAAAA+P8AAAAAAAAAAAAAAAAA/gcAAAAAAAAAAAAAAAAA+B8AAAAAAAAAAAAAAAAA/wAAAAAAAAAAAAAAAACADwAAAAAAAAAAAAAAAADwAAAAAA==",
});

export const isNorthAmericaLand = northAmericaMask.isLand.bind(northAmericaMask);
export const northAmericaTileLatLon = northAmericaMask.tileLatLon.bind(northAmericaMask);
